### ISSUE TITLE
TrackB Bug

### ISSUE THREAD

**Issue by yaohengzhi** [goucejia/ctdar_measurement_tool#2]
While evaluating TrackB, we will run into eval.evaluate_result_str(). However, there is a bug in it:
 ```
 for gtt in gt_remaining:
            for rest in remaining_tables:
                # note: for structural analysis, use 0.8 for table mapping
                if gtt.compute_table_iou(rest) >= table_iou_value:
                    table_matches.append((gtt, rest))
                    remaining_tables.remove(rest)   # unsafe... should be ok with the break below
                    gt_remaining.remove(gtt)
                    break
```
I run the the code with sample result & annotation. For test2-reg-result.xml, the result and annotation are identical. But we get a result with error. The code showed above can't match multiple tables. Since it's removed some element in `gt_remaining` while in for loop `for gtt in gt_remaining`.
Should be modified to:
```
        for gtt in gt_tables:
            for rest in result_tables:
                # note: for structural analysis, use 0.8 for table mapping
                if gtt.compute_table_iou(rest) >= table_iou_value:
                    table_matches.append((gtt, rest))
                    remaining_tables.remove(rest)   # unsafe... should be ok with the break below
                    gt_remaining.remove(gtt)
                    break
```

**Comment by goucejia** [comment]
Hello, you should try to use the updated version available at https://github.com/cndplab-founder/ctdar_measurement_tool. Thank you for reporting the issue.

**Comment by yaohengzhi** [comment]
issue is closed in that repo

> Hello, you should try to use the updated version available at https://github.com/cndplab-founder/ctdar_measurement_tool. Thank you for reporting the issue.
